version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: events_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventos_network
    restart: unless-stopped

  # Opcional: Añadir interfaz admin para la base de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: events_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - eventos_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  eventos_network:
    driver: bridge